image: docker:19.03.2

services:
  - docker:19.03.2-dind

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_NAME: "MyPythonApp"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run -d --name $CONTAINER_NAME $CONTAINER_TEST_IMAGE
    - docker exec $CONTAINER_NAME bash -c "python app/test.py"
